### ISSUE TITLE
Is it possible to support foxy?

### ISSUE THREAD

**Issue by zhexuany** [facontidavide/rosx_introspection#12]
I want to know is this project can be compiled or ran in Ros2 foxy?

If no, how can we make it work at foxy?

**Comment by zhexuany** [comment]
@facontidavide Sorry to ping you, but want to know the way to make it work under ros foxy

**Comment by facontidavide** [comment]
Foxy is end of life. I will accept Prs that offer backward compatiblity, but i will not work on that myself.
