### ISSUE TITLE
ROS 2 PointCloud2 data field does not get recognized as blob

### ISSUE THREAD

**Issue by andre-nguyen** [facontidavide/rosx_introspection#13]
I'm trying to deserialize a ROS 2 PointCloud2 stored in an mcap file. The data type of the data field is `UINT8` and `_is_array` is correctly set to `true`. 

However the condition in ros_parser.cpp#L127-L128
https://github.com/facontidavide/rosx_introspection/blob/648a50a04a8e9bb09a96695afb004a24338041fd/src/ros_parser.cpp#L127-L128

Is to check that the array is too large _and_ that the field is type other. I'm wondering, is the condition wrong and it should be an `or` or are array types supposed to be parsed as a `BuiltinType::OTHER`?

For what its worth, I'm using the message definitions stored in the mcap file itself.

**Comment by facontidavide** [comment]
good catch! that looks wrong. I will fix it
